### ISSUE TITLE
Proxy setting issue

### ISSUE THREAD

**Issue by ZhuojingXie** [tasos-py/Search-Engines-Scraper#2]
trying to using this great tool in my office. my company is using proxy for browsers. i tried input our server/port name in config file, and run into an SSL error?
is there a way to disable verify?

**Comment by tasos-py** [comment]
This library uses [requests](https://requests.kennethreitz.org/en/master/) for its connections to web-servers and proxies, and SSL Verification can be disabled simply by setting a `verify` parameter to false. The client (a `requests.session` object) can be accessed with `engine._http.client` and we can use it to set SSL and other parameters. For example, this is how you would disable verification for a `Google` object:
```
from search_engines import Google

engine = Google()
engine._http.client.verify = False
results = engine.search("query")
```
But note that disabling SSL Verification may be a security risk, because it opens the possibility of MITM attacks.  It would be much better to set a custom certificate (the company's certificate, for example), if that option is available. This can be done with the same mathod, but using the path to a certificate instead of a boolean, 
```
...
engine._http.client.verify = '/path/to/certfile'
...
```
For more details on this topic see [requests, ssl-cert-verification](https://requests.kennethreitz.org/en/master/user/advanced/#ssl-cert-verification).

**Comment by ZhuojingXie** [comment]
it is really helpful. Thank you very much

**Comment by tasos-py** [comment]
Glad to be of help! This issue made me think that maybe I should document some parts better, so thank you for that.
